# Generated by Django 4.2.1 on 2023-06-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0007_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                limit_choices_to={"is_public": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="instagram.post",
            ),
        ),
    ]
